#!/usr/bin/env python3
"""Export Eric's own X posts to content/x-posts.json.

Two inputs, either one works:

  API      X API v2 user timeline. Needs a bearer token in the environment variable
           X_BEARER_TOKEN. The token is never printed or written to the output file.
           If it is absent the script says so and exits without writing anything.

  Archive  The official X data archive: pass the downloaded zip, or the tweets.js
           inside it, with --archive.

Output shape (content/x-posts.json):

  {"account": "EricBuess", "source": "api"|"archive", "generated": "<UTC ISO>",
   "posts": [{"id", "date", "text", "url", "media": [...], "reply_to": "<id>"}]}

Replies are kept, because tools/x-categorize.py reads `cat:<category>` replies from
them. Retweets are excluded: they are not Eric's own posts.

Stdlib only. No posting, no writes to X, read-only.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
import urllib.error
import urllib.parse
import urllib.request
import zipfile
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_OUT = REPO_ROOT / "content" / "x-posts.json"
API_ROOT = "https://api.x.com/2"
TOKEN_ENV = "X_BEARER_TOKEN"


# ---------------------------------------------------------------- shared helpers


def rel(path: Path) -> str:
    """Repository-relative for readable messages, absolute when the path is elsewhere."""
    try:
        return str(path.resolve().relative_to(REPO_ROOT))
    except ValueError:
        return str(path)


def iso_day(value: str) -> str:
    """Return YYYY-MM-DD from an ISO 8601 timestamp, or the input unchanged."""
    match = re.match(r"^(\d{4}-\d{2}-\d{2})", value or "")
    return match.group(1) if match else (value or "")


def post_url(username: str, post_id: str) -> str:
    return f"https://x.com/{username}/status/{post_id}"


def write_posts(out_path: Path, username: str, source: str, posts: list[dict], dry_run: bool) -> None:
    seen: dict[str, dict] = {}
    for post in posts:
        seen[post["id"]] = post
    ordered = sorted(seen.values(), key=lambda post: (post.get("date") or "", post["id"]), reverse=True)
    payload = {
        "note": "Generated by tools/x-export.py. Each post is {id, date, text, url, media[], reply_to?}.",
        "account": username,
        "source": source,
        "generated": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "posts": ordered,
    }
    replies = sum(1 for post in ordered if post.get("reply_to"))
    if dry_run:
        print(f"dry run: {len(ordered)} posts ({replies} replies) from {source}; {rel(out_path)} not written")
        return
    out_path.parent.mkdir(parents=True, exist_ok=True)
    temp = out_path.with_suffix(out_path.suffix + ".tmp")
    temp.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    temp.replace(out_path)
    print(f"wrote {rel(out_path)}: {len(ordered)} posts ({replies} replies) from {source}")


# -------------------------------------------------------------------- API input


def api_get(path: str, params: dict, token: str, timeout: float) -> dict:
    url = f"{API_ROOT}{path}?{urllib.parse.urlencode(params)}"
    request = urllib.request.Request(url, headers={"Authorization": f"Bearer {token}", "User-Agent": "x-export/1.0"})
    try:
        with urllib.request.urlopen(request, timeout=timeout) as response:
            return json.loads(response.read().decode("utf-8"))
    except urllib.error.HTTPError as error:
        detail = error.read().decode("utf-8", "replace")[:300]
        # The request URL and headers are deliberately not echoed, so the token cannot leak.
        raise SystemExit(f"X API returned HTTP {error.code} for {path}: {detail}") from None
    except urllib.error.URLError as error:
        raise SystemExit(f"X API request for {path} failed: {error.reason}") from None


def api_export(username: str, limit: int, timeout: float) -> tuple[str, list[dict]] | None:
    token = os.environ.get(TOKEN_ENV, "").strip()
    if not token:
        print(
            f"No {TOKEN_ENV} in the environment, so the API input is skipped. "
            "Either export a bearer token, or pass the official X archive with "
            "--archive path/to/twitter-archive.zip.",
            file=sys.stderr,
        )
        return None

    user = api_get(f"/users/by/username/{urllib.parse.quote(username)}", {"user.fields": "id"}, token, timeout)
    user_id = (user.get("data") or {}).get("id")
    if not user_id:
        raise SystemExit(f"X API did not return an id for @{username}: {json.dumps(user)[:300]}")

    posts: list[dict] = []
    pagination: str | None = None
    while len(posts) < limit:
        params = {
            "max_results": min(100, max(5, limit - len(posts))),
            "exclude": "retweets",
            "tweet.fields": "created_at,text,referenced_tweets,attachments",
            "expansions": "attachments.media_keys",
            "media.fields": "type,url,preview_image_url",
        }
        if pagination:
            params["pagination_token"] = pagination
        page = api_get(f"/users/{user_id}/tweets", params, token, timeout)
        media_by_key = {
            item.get("media_key"): item.get("url") or item.get("preview_image_url")
            for item in (page.get("includes") or {}).get("media", [])
        }
        for tweet in page.get("data") or []:
            post = {
                "id": str(tweet.get("id")),
                "date": tweet.get("created_at") or "",
                "text": tweet.get("text") or "",
                "url": post_url(username, str(tweet.get("id"))),
                "media": [
                    media_by_key[key]
                    for key in (tweet.get("attachments") or {}).get("media_keys", [])
                    if media_by_key.get(key)
                ],
            }
            for reference in tweet.get("referenced_tweets") or []:
                if reference.get("type") == "replied_to":
                    post["reply_to"] = str(reference.get("id"))
            posts.append(post)
        pagination = (page.get("meta") or {}).get("next_token")
        if not pagination:
            break
    return "api", posts[:limit]


# ---------------------------------------------------------------- archive input


ARCHIVE_DATE = "%a %b %d %H:%M:%S %z %Y"


def parse_tweets_js(text: str) -> list[dict]:
    """The archive files are JSON prefixed with `window.YTD.tweets.part0 = `."""
    start = text.find("[")
    if start < 0:
        raise SystemExit("no JSON array found in the archive tweets file")
    return json.loads(text[start:])


def archive_records(path: Path) -> list[dict]:
    if zipfile.is_zipfile(path):
        with zipfile.ZipFile(path) as archive:
            names = [
                name
                for name in archive.namelist()
                if re.search(r"(^|/)tweets(-part\d+)?\.js$", name) or name.endswith("/tweet.js")
            ]
            if not names:
                raise SystemExit(f"{path} contains no data/tweets.js; is this the official X archive zip?")
            records: list[dict] = []
            for name in sorted(names):
                records.extend(parse_tweets_js(archive.read(name).decode("utf-8", "replace")))
            return records
    return parse_tweets_js(path.read_text(encoding="utf-8", errors="replace"))


def archive_export(path: Path, username: str, limit: int) -> tuple[str, list[dict]]:
    posts: list[dict] = []
    for record in archive_records(path):
        tweet = record.get("tweet", record) if isinstance(record, dict) else None
        if not isinstance(tweet, dict):
            continue
        text = tweet.get("full_text") or tweet.get("text") or ""
        if text.startswith("RT @"):
            continue
        post_id = str(tweet.get("id_str") or tweet.get("id") or "").strip()
        if not post_id:
            continue
        raw_date = tweet.get("created_at") or ""
        try:
            stamp = datetime.strptime(raw_date, ARCHIVE_DATE).astimezone(timezone.utc)
            date = stamp.strftime("%Y-%m-%dT%H:%M:%SZ")
        except ValueError:
            date = raw_date
        media = [
            item.get("media_url_https") or item.get("media_url")
            for group in (tweet.get("extended_entities"), tweet.get("entities"))
            for item in ((group or {}).get("media") or [])
            if item.get("media_url_https") or item.get("media_url")
        ]
        post = {
            "id": post_id,
            "date": date,
            "text": text,
            "url": post_url(username, post_id),
            "media": list(dict.fromkeys(media)),
        }
        reply_to = tweet.get("in_reply_to_status_id_str") or tweet.get("in_reply_to_status_id")
        if reply_to:
            post["reply_to"] = str(reply_to)
        posts.append(post)
    posts.sort(key=lambda post: (post.get("date") or "", post["id"]), reverse=True)
    return "archive", posts[:limit]


# ----------------------------------------------------------------------- driver


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--user", default="EricBuess", help="X handle without @ (default: EricBuess)")
    parser.add_argument("--archive", type=Path, help="official X archive zip, or the tweets.js inside it")
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT, help="output path (default: content/x-posts.json)")
    parser.add_argument("--max", type=int, default=800, dest="limit", help="stop after this many posts")
    parser.add_argument("--timeout", type=float, default=30.0, help="API timeout in seconds")
    parser.add_argument("--dry-run", action="store_true", help="report what would be written and stop")
    args = parser.parse_args(argv)

    if args.archive:
        if not args.archive.exists():
            raise SystemExit(f"archive not found: {args.archive}")
        source, posts = archive_export(args.archive, args.user, args.limit)
    else:
        result = api_export(args.user, args.limit, args.timeout)
        if result is None:
            return 0
        source, posts = result

    if not posts:
        print("no posts found; nothing written", file=sys.stderr)
        return 0
    write_posts(args.out, args.user, source, posts, args.dry_run)
    print("next: python3 tools/x-categorize.py")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
